name: Step 1 # Enable scanning

on:
  push:
    paths:
     - credentials.yml

permissions:
  contents: read
  actions: write
  issues: write

env:
  STEP_2_FILE: ".github/steps/2-review-alerts.md"

jobs:
  find_exercise:
    name: Find Exercise Issue
    uses: skills/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.3.0

  check_step_work:
    name: Check if secret scanning is enabled
    needs: [find_exercise]
    runs-on: ubuntu-latest
    env:
      ISSUE_URL: ${{ needs.find_exercise.outputs.issue-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Get response templates
        if: true
        uses: actions/checkout@v4
        with:
          repository: skills/response-templates
          path: skills-response-templates

      - name: Update comment - checking work
        if: false
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file skills-response-templates/step-feedback/checking-work.md \
            --edit-last
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # START: Check practical exercise 

      - name: Check if secret scanning is enabled
        id: check-secret-scanning-enabled
        uses: skills/exercise-toolkit/.github/workflows/grading/check-repo-setting@cwb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          check-name: "Secret Scanning Enabled"
          setting-name: "security_and_analysis.secret_scanning.status"
          setting-expected-value: "enabled"
          pass-message: "Verified"
          fail-message: "Secret scanning should be enabled. Please check your repository settings."

      - name: Check if secret push protection is disabled
        id: check-secret-push-protection-disabled
        uses: skills/exercise-toolkit/.github/workflows/grading/check-repo-setting@cwb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          check-name: "Secret Protection Disabled"
          setting-name: "security_and_analysis.secret_scanning_push_protection.status"
          setting-expected-value: "disabled"
          pass-message: "Verified"
          fail-message: "Secret push protection should be disabled for this exercise step. Please check your repository settings."
        
      - name: Check credentials file
        id: check-credentials-file
        uses: actions/github-script@v7
        env:
          FILE: credentials.yml
          REQUIRED_WORDS: "AKIAQYLPMN5HNM4OZ56B, Rm29CHLQCeaT6V/Rsw3UFWW1/UWQ0lhsWBa3bdca"
        with:
          result-encoding: string
          script: |
            const fs = require('fs');
            
            const test = {
              "name": "credentials.yml",
              "passed": false,
              "message": ""
            }

            // Check if the file exists
            const file = process.env.FILE;
            if (!fs.existsSync(file)) {
              test.message = "File not found. Please try again.";
              return JSON.stringify(test);
            }

            // Read the file content
            const fileContent = fs.readFileSync('credentials.yml', 'utf8');

            // Load the required words and trim
            const requiredWords = process.env.REQUIRED_WORDS.split(',').map(word => word.trim());
            
            // Provide feedback
            test.passed = true;
            test.message = "";
            for (const word of requiredWords) {
              if (!fileContent.includes(word)) {
                test.passed = false;
                test.message = `File was not updated as expected. Please try again.`;
                break;
              }
            }
            
            // Return the checks object as a JSON string
            return JSON.stringify(test);

      - name: Check all results
        id: check-combined-results
        uses: skills/exercise-toolkit/.github/workflows/grading/check-all-results@cwb
        env:
          check-1: ${{ steps.check-secret-scanning-enabled.outputs.result }}
          check-2: ${{ steps.check-secret-push-protection-disabled.outputs.result }}
          check-3: ${{ steps.check-credentials-file.outputs.result }}

      - name: Build message - step results
        id: build-message-step-results
        uses: skills/action-text-variables@v1
        with:
          template-file: skills-response-templates/step-feedback/step-results.md
          template-vars: '{
              "step_number": 1,
              "passed": ${{ steps.check-combined-results.outputs.result }},
              "results_table": [
                  ${{ steps.check-secret-scanning-enabled.outputs.result }},
                  ${{ steps.check-secret-push-protection-disabled.outputs.result }},
                  ${{ steps.check-credentials-file.outputs.result }}
                ],
              "tips": [
              "Secret scanning supports custom pattern searching. Give it a try!",
              "Unsure how to handle secrets for for GitHub Actions? Check out [the docs](https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions)."
              ]
            }'

      - name: Create comment - step results
        run: |
          gh issue comment "$ISSUE_URL" \
            --body "$COMMENT_BODY" \
            --edit-last
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_BODY: ${{ steps.build-message-step-results.outputs.updated-text }}

      - name: Fail job if not all checks passed
        if: steps.check-combined-results.outputs.result == 'false'
        run: exit 1

      # END: Check practical exercise

      - name: Create comment - step results
        run: |
          gh issue comment "$ISSUE_URL" \
            --body "Great job enabling secret scanning! 🎉 Now your repository will automatically detect any committed secrets."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build message - step finished
        id: build-message-step-finish
        uses: skills/action-text-variables@v1
        with:
          template-file: skills-response-templates/step-feedback/step-finished-prepare-next-step.md
          template-vars: |
            next_step_number=2

      - name: Create comment - step finished
        run: |
          gh issue comment "$ISSUE_URL" \
            --body "$ISSUE_BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_BODY: ${{ steps.build-message-step-finish.outputs.updated-text }}

  post_next_step_content:
    name: Post next step content
    needs: [find_exercise, check_step_work]
    runs-on: ubuntu-latest
    env:
      ISSUE_URL: ${{ needs.find_exercise.outputs.issue-url }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/response-templates
          path: skills-response-templates

      - name: Create comment - add step content
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file "$STEP_2_FILE"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create comment - watching for progress
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file skills-response-templates/step-feedback/watching-for-progress.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable next workflow
        run: |
          gh workflow disable "Step 1" || true
          gh workflow enable "Step 2" || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}